repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
      - id: reorder-python-imports
        # https://peps.python.org/pep-0563/
        args: [--py310-plus, --add-import, 'from __future__ import annotations']

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
        entry: 'env DATABASE_URL=sqlite:///:memory: IS_MYPY=1 mypy'
        additional_dependencies:
          - django-stubs[compatible-mypy]==1.13.0
          # Forkeamos el repo de drf-stubs porque no se actualiza hace cinco meses y la última versión
          # no soporta mypy >0.970. A su vez, lockeamos la versión para que no se rompa al eliminar
          # el caché de pre-commit (las últimas versiones del upstream no están pasando los tests en CI).
          - git+https://github.com/emicba/djangorestframework-stubs#egg=djangorestframework-stubs[compatible-mypy]

          # Eliminar las deps que no son stubs cuando se fixee esta issue
          # https://github.com/typeddjango/django-stubs/issues/1087#issuecomment-1208188250
          # tl;dr: django-stubs necesita configurar las apps de django para lintear entonces necesita las
          # dependencias como dj-database-url, rest_framework, etc 🙃
          - dj-database-url
          - djangorestframework
          - django-cors-headers
          - drf-spectacular
          - django-filter==22.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
      - id: debug-statements
