services:
  app:
    image: moni-score
    container_name: moni_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: moni_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - moni-score-db:/var/lib/postgresql/data

volumes:
  moni-score-db:
