version: '3.8'

services:
  backend:
    image: score-backend
    container_name: score_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    image: score-frontend
    container_name: score_frontend
    build:
      context: ../moni_score_test_front
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend

  db:
    image: postgres:15.2-alpine
    container_name: moni_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - moni-score-db:/var/lib/postgresql/data

volumes:
  moni-score-db:
