# Generated by Django 4.2.10 on 2024-02-08 18:59
from __future__ import annotations

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
                ),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                (
                    'dni',
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[0-9]{7}[0-9]?$'),
                                message='%(value)r no es un DNI válido.',
                            )
                        ],
                    ),
                ),
                ('email', models.EmailField(help_text='Email de contacto.', max_length=254)),
                (
                    'genero',
                    models.CharField(
                        choices=[('M', 'Masculino'), ('F', 'Femenino'), ('D', 'Desconocido')],
                        default='D',
                        max_length=1,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
                ),
                ('status', models.IntegerField(choices=[(0, 'Rechazado'), (1, 'Aprobado')])),
                (
                    'persona',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scores',
                        to='scoring.persona',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Scores',
            },
        ),
    ]
